[package]
name = "seroost"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
serde = "1.0.217"
serde_json = "1.0.135"
tiny_http = "0.12.0"
walkdir = "2.5.0"
xml-rs = "0.8.25"
